### ISSUE TITLE
Write better Regex

### ISSUE THREAD

**Issue by Niecke** [Niecke/logstash-filter-panfinder#8]
A new Regex based on the data from https://baymard.com/checkout-usability/credit-card-patterns

## ToDo
* [x] Visa 
```
(4\d{3}.?(\d{4}.?){3})
```
* [x] Visa Electron (like Visa)
Is a subset of Visa.
* [x] American Express 
```
((34|37)\d{2}.?\d{6}.?\d{5})
```
* [ ] China UnionPay
* [x] MasterCard 
```
(5[1-5]\d{2}.?(\d{4}.?){3})|
(2[2-7]\d{2}.?(\d{4}.?){3})
```
* [x] Maestro
```
(50\d{2}|5[6-8]\d{2}|6\d{3}).?(\d{4}.?\d{4}.?\d{4}(\d{3})?|\d{6}.?\d{5}|\d{4}.?\d{5})
```
* [x] Diners Club Carte Blanche
Is a subset of Diners Club International.
* [x] Diners Club International
```
30[0-5].?(\d{6}).?(\d{4})
```
Test Data
```
299 111111 2222 # fail
300 111111 2222 # ok
301 111111 2222 # ok
305 111111 2222 # ok
306 111111 2222 # fail
```
* [x] Diners Club United States & Canada 
```
5[4-5]\d{2}.?(\d{4}).?(\d{4}).?(\d{4})
```
Test Data
```
5311 2222 3333 4444 # fail
5411 2222 3333 4444 # ok
5511 2222 3333 4444 # ok
5611 2222 3333 4444 # fail
```
* [x] Discover
```
6((011|22[1-9]|4[4-9]\d|5\d{2})(.?\d{4}){3})
```
```
6010 2222 3333 4444 fail
6011 2222 3333 4444 ok
6221 2622 3333 4444 ok
6229 2522 3333 4444 ok
6431 2222 3333 4444 fail
6441 2222 3333 4444 ok
6491 2222 3333 4444 ok
6511 2222 3333 4444 ok
```
* [ ] JCB 
* [ ] UATP
* [ ] Dankort
* [ ] InterPayment
